name: Main Workflow
on:
  push:
    branches:
      - mana

jobs:
  configure_aws_credentials:
    name: Configure AWS Credentials
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

  terraform_init:
    name: Terraform Init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

  # Terraform Apply section is commented out
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  # delay_job:
  #   name: Delay Job
  #   runs-on: ubuntu-latest
  #   needs: terraform_plan
  #   steps:
  #     - name: Wait for 1 minute
  #       run: sleep 60

  # terraform_destroy:
  #   name: Terraform Destroy
  #   runs-on: ubuntu-latest
  #   needs: delay_job
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  
