name: Main Workflow
on:
  push:
    branches:
      - mana

jobs:
  configure_aws_credentials:
    name: Configure AWS Credentials
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

  terraform_init:
    name: Terraform Init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./workflow

  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: [terraform_init]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./workflow

  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: [terraform_plan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./workflow

  # terraform_destroy:
  #   name: Terraform Destroy
  #   runs-on: ubuntu-latest
  #   needs: [terraform_apply]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Terraform Destroy
  #       run: terraform destroy -auto-approve
  #       working-directory: ./path/to/terraform/directory
