name: Main Workflow
on:
  push:
    branches:
      - mana

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Include workflow1.yml (Terraform apply)
      - name: Run Terraform Apply
        uses: actions/checkout@v2
        with:
          repository: ManasaBhat4/workflow
          path: .github/workflows/workflowm.yml

  delay_job:
    runs-on: ubuntu-latest
    needs: terraform_apply
    steps:
      - name: Wait for 2 minutes
        run: sleep 120

  terraform_destroy:
    runs-on: ubuntu-latest
    needs: delay_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Include workflow2.yml (Terraform destroy)
      - name: Run Terraform Destroy
        uses: actions/checkout@v2
        with:
          repository: ManasaBhat4/workflow
          path: .github/workflows/workflowma.yml
