name: Main Workflow
on:
  push:
    branches:
      - mana

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Include workflow1.yml (Terraform apply)
      - name: Run Terraform Apply
        run: |
          cd .github/workflow/workflowm
          # Assuming you have Terraform installed and configured
          terraform init
          terraform apply -auto-approve
        working-directory: .github/workflow/workflowm

  delay_job:
    runs-on: ubuntu-latest
    needs: terraform_apply
    steps:
      - name: Wait for 2 minutes
        run: sleep 120

  terraform_destroy:
    runs-on: ubuntu-latest
    needs: delay_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Include workflow2.yml (Terraform destroy)
      - name: Run Terraform Destroy
        run: |
          cd .github/workflow/workflowma
          # Assuming you have Terraform installed and configured
          terraform init
          terraform destroy -auto-approve
        working-directory: .github/workflow/workflowma
