name: Main Workflow
on:
  push:
    branches:
      - mana

      

jobs:
- name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

  terraform_init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2           

      # # Include workflow1.yml (Terraform apply)
      # #- name: Run Terraform Apply
      #  # uses: actions/checkout@v2
      #  # with:
      #     repository: ManasaBhat4/workflow
      #     path: .github/workflows/workflowm.yml

  delay_job:
    runs-on: ubuntu-latest
    needs: terraform_apply
    steps:
      - name: Wait for 1 minutes
        run: sleep 60

  terraform_destroy:
    runs-on: ubuntu-latest
    needs: delay_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # # Include workflow2.yml (Terraform destroy)
      # - name: Run Terraform Destroy
      #   uses: actions/checkout@v2
      #   with:
      #     repository: ManasaBhat4/workflow
      #     path: .github/workflows/workflowma.yml
